Repository mongodb/docs-kotlin, pull requests merged in 2023-05, with the labels that each got.

#63 (DOCSP-29244, DOCSP-29245, DOCSP-29246): Delete Usage Example pages
  examples/src/main/kotlin/usageExamples/delete/delete.kt
  examples/src/main/kotlin/usageExamples/deleteMany/deleteMany.kt
  source/examples/generated/delete.snippet.delete-usage-example.kt
  source/examples/generated/deleteMany.snippet.delete-many-usage-example.kt
  source/usage-examples/delete-operations.txt
  source/usage-examples/deleteMany.txt
  source/usage-examples/deleteOne.txt
Labels: Try to Have, Usage Example

#47 (DOCSP-29224): Data class document data type
  examples/src/test/kotlin/DataClassTest.kt
  source/examples/generated/DataClassTest.snippet.annotated-data-class.kt
  source/examples/generated/DataClassTest.snippet.data-class.kt
  source/examples/generated/DataClassTest.snippet.insert-annotated-data-class.kt
  source/examples/generated/DataClassTest.snippet.insert-data-class.kt
  source/examples/generated/DataClassTest.snippet.recursive-data-class-types-retrieve.kt
  source/examples/generated/DataClassTest.snippet.recursive-data-class-types.kt
  source/examples/generated/DataClassTest.snippet.retrieve-annotated-data-class.kt
  source/examples/generated/DataClassTest.snippet.retrieve-data-class.kt
  source/fundamentals/data-formats.txt
  source/fundamentals/data-formats/document-data-format-data-class.txt
Labels: Must Have

#53 (DOCSP-29265): Sorts Builders page for Kotlin
  examples/src/test/kotlin/SortTest.kt
  source/examples/generated/SortTest.snippet.combine-sort.kt
  source/fundamentals/builders.txt
  source/fundamentals/builders/sort.txt
  source/fundamentals/crud/read-operations/sort.txt
Labels: Try to Have

#50 (DOCSP-29237): Kotlin FAQ
  source/faq.draft
  source/faq.txt
  source/fundamentals/connection/connect.txt
  source/index.txt
Labels: Must Have

#76 (DOCSP-29259): What's New page
  source/index.txt
  source/whats-new.draft
  source/whats-new.txt
Labels: Try to Have
