Repository mongodb/docs-kotlin, pull requests merged in 2023-06, with the labels that each got.

#65 (DOCSP-29251, DOCSP-29252, DOCSP-29253): Insert Usage Example pages
  examples/src/main/kotlin/usageExamples/insert/InsertOne.kt
  examples/src/main/kotlin/usageExamples/insertMany/InsertMany.kt
  source/examples/generated/InsertMany.snippet.insert-many-usage-example.kt
  source/examples/generated/InsertOne.snippet.insert-usage-example.kt
  source/usage-examples/insert-operations.txt
  source/usage-examples/insertMany.txt
  source/usage-examples/insertOne.txt
Labels: Try to Have, Usage Example

#69 (DOCSP-29243): Count Usage Examples page
  examples/src/main/kotlin/usageExamples/count/Count.kt
  examples/src/test/kotlin/CountTest.kt
  source/examples/generated/Count.snippet.count-usage-example.kt
  source/examples/generated/CountTest.snippet.hint.kt
  source/usage-examples/count.txt
Labels: Try to Have, Usage Example

#64 (DOCSP-29238): Kotlin feild level encryption
  source/fundamentals.txt
  source/fundamentals/connection/mongoclientsettings.txt
  source/fundamentals/csfle.draft.rst
  source/fundamentals/encrypt-fields.txt
  source/includes/fundamentals-sections.rst
Labels: Try to Have

#49 (DOCSP-29167): Kotlin Flow docs
  examples/src/test/kotlin/FlowTest.kt
  examples/src/test/kotlin/TimeSeriesTest.kt
  source/examples/generated/FlowTest.snippet.count.kt
  source/examples/generated/FlowTest.snippet.explain.kt
  source/examples/generated/FlowTest.snippet.first.kt
  source/examples/generated/FlowTest.snippet.firstOrNull.kt
  source/examples/generated/FlowTest.snippet.iterate.kt
  source/examples/generated/FlowTest.snippet.toList.kt
  source/fundamentals/crud/read-operations.txt
  source/fundamentals/crud/read-operations/cursor.draft.rst
  source/fundamentals/crud/read-operations/flow.txt
  source/quick-reference.txt
  source/usage-examples/distinct.txt
  source/usage-examples/find.txt
  source/usage-examples/findOne.txt
Labels: Must Have

#54 (DOCSP-29266): Kotlin Updates Builder
  examples/src/test/kotlin/UpdatesBuildersTest.kt
  source/examples/generated/UpdatesBuildersTest.snippet.add-to-set-update.kt
  source/examples/generated/UpdatesBuildersTest.snippet.bitwise-or-update.kt
  source/examples/generated/UpdatesBuildersTest.snippet.combine-update.kt
  source/examples/generated/UpdatesBuildersTest.snippet.current-date-update.kt
  source/examples/generated/UpdatesBuildersTest.snippet.current-timestamp-update.kt
  source/examples/generated/UpdatesBuildersTest.snippet.example-data-class.kt
  source/examples/generated/UpdatesBuildersTest.snippet.inc-update.kt
  source/examples/generated/UpdatesBuildersTest.snippet.max-update.kt
  source/examples/generated/UpdatesBuildersTest.snippet.min-update.kt
  source/examples/generated/UpdatesBuildersTest.snippet.mul-update.kt
  source/examples/generated/UpdatesBuildersTest.snippet.pop-first-update.kt
  source/examples/generated/UpdatesBuildersTest.snippet.pull-all-update.kt
  source/examples/generated/UpdatesBuildersTest.snippet.pull-update.kt
  source/examples/generated/UpdatesBuildersTest.snippet.push-update.kt
  source/examples/generated/UpdatesBuildersTest.snippet.rename-update.kt
  source/examples/generated/UpdatesBuildersTest.snippet.set-on-insert-update.kt
  source/examples/generated/UpdatesBuildersTest.snippet.set-update.kt
  source/examples/generated/UpdatesBuildersTest.snippet.unset-update.kt
  source/fundamentals/builders.txt
  source/fundamentals/builders/updates.txt
Labels: Try to Have

#48 (DOCSP-29226): KotlinX Serialization
  examples/build.gradle.kts
  examples/src/test/kotlin/KotlinXSerializationTest.kt
  snooty.toml
  source/examples/generated/KotlinXSerializationTest.snippet.basic-serialization.kt
  source/examples/generated/KotlinXSerializationTest.snippet.custom-serialization.kt
  source/fundamentals/data-formats.txt
  source/fundamentals/data-formats/codecs.txt
  source/fundamentals/data-formats/serialization.txt
Labels: Must Have
